Repository YAPP-Github/24th-App-Team-3-iOS, pull requests merged in 2024-06, with the labels that each got.

#2 [Doc] 개발 컨벤션 관련 문서 기재
  Docs/issue_proccess.md
  README.md
Labels: :memo: Docs

#17 [Docs] #4 이슈 템플릿, PR 템플릿 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/default_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactoring_request.md
  .github/pull_request_template.md
Labels: :memo: Docs

#14 Feature/#10 social login dev
  ShowPot/Podfile
  ShowPot/Podfile.lock
  ShowPot/ShowPot/Application/AppDelegate.swift
  ShowPot/ShowPot/Application/SceneDelegate.swift
  ShowPot/ShowPot/Presentation/Scene/Login/ViewController/LoginViewController.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/kakao_login_medium_narrow.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/kakao_login_medium_narrow.imageset/kakao_login_medium_narrow.png
  ShowPot/ShowPot/Resource/Info.plist
Labels: :sparkles: Feature

#21 [Feature] #15 ViewController & ViewModel 정형화
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Presentation/Common/BaseViewController.swift
  ShowPot/ShowPot/Presentation/Common/ViewHolderType.swift
  ShowPot/ShowPot/Presentation/Common/ViewModelType.swift
  ShowPot/ShowPot/Presentation/Scene/Login/Coordinator/LoginCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Login/ViewController/LoginViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Login/ViewHolder/LoginViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Login/ViewModel/LoginViewModel.swift
Labels: :sparkles: Feature

#23 [Feature] #20 Logger를 활용한 Common 로그기능 개발
  ShowPot/Podfile.lock
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Environment.swift
  ShowPot/ShowPot/Common/LogHelper.swift
  ShowPot/ShowPot/Presentation/Scene/Login/ViewController/LoginViewController.swift
Labels: :sparkles: Feature

#26 [Feature] #25 ShowPot프로젝트 디자인 리소스 추가
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/UIFont+Extension.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Error/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Error/error.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object_Line_TextColor/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object_Line_TextColor/gray100.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object_Line_TextColor/gray200.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object_Line_TextColor/gray300.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object_Line_TextColor/gray400.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object_Line_TextColor/gray500.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object_Line_TextColor/gray600.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object_Line_TextColor/gray700.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object_Line_TextColor/gray800.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Primary_Brand_Color/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Primary_Brand_Color/mainBlue.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Primary_Brand_Color/mainGreen.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Primary_Brand_Color/mainOrange.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Primary_Brand_Color/mainYellow.colorset/Contents.json
  ShowPot/ShowPot/Resource/Font/Oswald/Oswald-Bold.ttf
  ShowPot/ShowPot/Resource/Font/Oswald/Oswald-ExtraLight.ttf
  ShowPot/ShowPot/Resource/Font/Oswald/Oswald-Light.ttf
  ShowPot/ShowPot/Resource/Font/Oswald/Oswald-Medium.ttf
  ShowPot/ShowPot/Resource/Font/Oswald/Oswald-Regular.ttf
  ShowPot/ShowPot/Resource/Font/Oswald/Oswald-SemiBold.ttf
  ShowPot/ShowPot/Resource/Font/Pretendard/Pretendard-Black.otf
  ShowPot/ShowPot/Resource/Font/Pretendard/Pretendard-Bold.otf
  ShowPot/ShowPot/Resource/Font/Pretendard/Pretendard-ExtraBold.otf
  ShowPot/ShowPot/Resource/Font/Pretendard/Pretendard-ExtraLight.otf
  ShowPot/ShowPot/Resource/Font/Pretendard/Pretendard-Light.otf
  ShowPot/ShowPot/Resource/Font/Pretendard/Pretendard-Medium.otf
  ShowPot/ShowPot/Resource/Font/Pretendard/Pretendard-Regular.otf
  ShowPot/ShowPot/Resource/Font/Pretendard/Pretendard-SemiBold.otf
  ShowPot/ShowPot/Resource/Font/Pretendard/Pretendard-Thin.otf
  ShowPot/ShowPot/Resource/Info.plist
Labels: :sparkles: Feature

#27 [Feature] #25 폰트 관리를 위한 코드 추가
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/Sample+Extension.swift
  ShowPot/ShowPot/Common/Extension/UIFont+Extension.swift
  ShowPot/ShowPot/Common/Font/CustomFont.swift
  ShowPot/ShowPot/Common/Font/ENFont.swift
  ShowPot/ShowPot/Common/Font/KRFont.swift
  ShowPot/ShowPot/Common/Font/LanguageFont.swift
Labels: :sparkles: Feature

#29 [Refactor] #20 기존 Common 로그 코드 개선
  ShowPot/ShowPot/Presentation/Common/BaseViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Login/ViewController/LoginViewController.swift
Labels: :recycle: Refactor

#30 [Package] #18 Cocoapods -> SPM으로 의존성관리도구 변경
  ShowPot/Podfile
  ShowPot/Podfile.lock
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot.xcworkspace/contents.xcworkspacedata
  ShowPot/ShowPot.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ShowPot/ShowPot/Resource/Configuration/ShowPot-Debug.xcconfig
  ShowPot/ShowPot/Resource/Configuration/ShowPot-Release.xcconfig
Labels: :package: Package

#31 [Package] #16 flexlayout, pinlayout 패키지 추가
  ShowPot/ShowPot.xcodeproj/project.pbxproj
Labels: :package: Package

#32 [Config] #8 Localizable을 SwiftGen이용해 자동화 설정
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
  ShowPot/swiftgen.yml
Labels: :wrench: Config

#35 [Refactor] #25 피그마 잘못된 녹색 색상 기재로 인한 변경
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Primary_Brand_Color/mainGreen.colorset/Contents.json
Labels: :recycle: Refactor
