Repository YAPP-Github/24th-App-Team-3-iOS, pull requests merged in 2024-08, with the labels that each got.

#90 [Refactor] #76 폰트 관리 및 적용 기능 코드 리팩토링
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/NSAttributedString+Extension.swift
  ShowPot/ShowPot/Common/Extension/UIFont+Extension.swift
  ShowPot/ShowPot/Common/Extension/UILabel+Extension.swift
  ShowPot/ShowPot/Common/Font/CustomFont.swift
  ShowPot/ShowPot/Common/Font/ENFont.swift
  ShowPot/ShowPot/Common/Font/KRFont.swift
  ShowPot/ShowPot/Common/Font/LanguageFont.swift
  ShowPot/ShowPot/Common/UI/Base/PaddingLabel.swift
  ShowPot/ShowPot/Common/UI/Base/SnackBar.swift
  ShowPot/ShowPot/Common/UI/SPButton.swift
  ShowPot/ShowPot/Common/UI/SPButtonStyle.swift
  ShowPot/ShowPot/Common/UI/SPLabel.swift
  ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/CustomView/OnboardingCarouselCell.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedOnlyTitleHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceWithTicketOnSaleSoonCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedRecommendedPerformanceCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSearchButton.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWatchTheFullPerformanceFooterView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWithButtonHeaderView.swift
Labels: :recycle: Refactor

#91 [Feature] #67 검색화면 구현 및 로직 작성
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/UI/Layout/LeftAlignedCollectionViewFlowLayout.swift
  ShowPot/ShowPot/Data/UserDefaults/UserDefaultsKey.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Search/CustomView/FeaturedRecentSearchCell.swift
  ShowPot/ShowPot/Presentation/Scene/Search/CustomView/FeaturedRecentSearchHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Search/CustomView/FeaturedSearchTextField.swift
  ShowPot/ShowPot/Presentation/Scene/Search/CustomView/PerformanceInfoCollectionViewCell.swift
  ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#98 #97 SPLabel 적용 후 baseline 안맞는 문제 해결
  ShowPot/ShowPot/Common/Extension/NSAttributedString+Extension.swift
  ShowPot/ShowPot/Common/UI/SPLabel.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/CustomView/OnboardingCarouselCell.swift
Labels: :bug: Bug

#94 [Feature] #93 티켓팅 공연 시간정보 칩 UI로 변경
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceWithTicketOnSaleSoonCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
Labels: :sparkles: Feature

#103 [Package] #102 PinLayout/FlexLayout 삭제 & RxDatasource/RxGesture 추가
  ShowPot/ShowPot.xcodeproj/project.pbxproj
Labels: :package: Package

#104 [Feature] #75 홈화면 상단 로고 & 검색 영역 개발
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/MainTabController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/NavigationController.swift
Labels: :sparkles: Feature

#100 [Feature] #96 전체공연 화면 UI 구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Domain/UseCase/AllPerformance/AllPerformanceUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/AllPerformance/DefaultAllPerformanceUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/AllPerformanceCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/AllPerformanceViewController.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/AllPerformanceViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/AllPerformanceViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/CustomView/AllPerformanceNavigationView.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/CustomView/CheckBoxButton.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/CustomView/PerformanceFilterHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceWithTicketOnSaleSoonCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_off.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_off.imageset/check=off.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_off.imageset/check=off@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_off.imageset/check=off@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_off.imageset/checkbox.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_off.imageset/checkbox@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_off.imageset/checkbox@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_on.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_on.imageset/check=on.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_on.imageset/check=on@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_on.imageset/check=on@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_on.imageset/checkbox.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_on.imageset/checkbox@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/Checkbox/ic_checkbox_on.imageset/checkbox@3x.png
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#113 [Feature] #112 아티스트구독 이미지 변경에 따른 코드 수정
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_alarm_complete.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_alarm_complete.imageset/ic_alarmcomplete_36.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_alarm_complete.imageset/ic_alarmcomplete_36@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_alarm_complete.imageset/ic_alarmcomplete_36@3x.png
Labels: :sparkles: Feature

#111 [Refactor] #95 DateFormatterFactory 구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/DateFormatterFactory.swift
  ShowPot/ShowPot/Presentation/Scene/Search/CustomView/PerformanceInfoCollectionViewCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWatchTheFullPerformanceFooterView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWithButtonHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
Labels: :recycle: Refactor

#118 [fix] #99 gray 컬러 일부 수정
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object Color/gray100.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object Color/gray200.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Object Color/gray300.colorset/Contents.json
Labels: :bug: Bug

#119 [Feature] #117 Splash Screen 개발
  ShowPot/ShowPot/Application/AppDelegate.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/app_icon.imageset/Appicon.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/app_icon.imageset/Appicon@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/app_icon.imageset/Appicon@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/app_icon.imageset/Contents.json
  ShowPot/ShowPot/Resource/Base.lproj/LaunchScreen.storyboard
Labels: :sparkles: Feature

#116 [Feature] #109 바텀시트 개발
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/BaseViewController+BottomSheet.swift
  ShowPot/ShowPot/Common/UI/Base/BottomSheetViewController.swift
  ShowPot/ShowPot/Common/UI/SPButtonStyle.swift
  ShowPot/ShowPot/Common/UI/SPDefaultBottomSheetViewController.swift
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#121 [Feature] #107 내공연알림설정화면 UI 구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/Date+Extension.swift
  ShowPot/ShowPot/Common/Extension/UIButton+Extension.swift
  ShowPot/ShowPot/Common/UI/Base/BottomSheetViewController.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/AlarmSettingBottomSheetViewController.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/SPDefaultBottomSheetViewController.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarmBottomSheetViewController.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarmBottomSheetViewModel.swift
  ShowPot/ShowPot/Domain/UseCase/MyShow/MyShowAlarmUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/MyShow/MyShowUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Search/CustomView/PerformanceInfoCollectionViewCell.swift
  ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/MyShowEmptyView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/ShowAlarmButtonView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/ShowAlarmCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/TicketingAlarmCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmViewModel.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/my_show_empty.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/my_show_empty.imageset/Frame 2608755.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/my_show_empty.imageset/Frame 2608755@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/my_show_empty.imageset/Frame 2608755@3x.png
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#130 [Feature] #124 마이페이지 UI 구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/NSAttributedString+Extension.swift
  ShowPot/ShowPot/Data/UserDefaults/UserDefaultsKey.swift
  ShowPot/ShowPot/Domain/UseCase/MyAlarm/DefaultMyAlarmUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/MyPage/MyPageUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/CustomView/MenuCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/CustomView/MyPageHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewModel.swift
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#134 [Feature] #131 티켓팅종료 및 관심공연 UI 구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Domain/UseCase/ClosedShow/ClosedShowUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/ClosedShow/DefaultClosedShowUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/InterestShow/DefaultInterestShowUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/InterestShow/InterestShowUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/MyAlarm/DefaultMyAlarmUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/ClosedShowListCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/ClosedShowListViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/ClosedShowListViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/ClosedShowListViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/CustomView/ClosedShowListEmptyView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/CustomView/MenuCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/CustomView/InterestShowListEmptyView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/CustomView/ShowDeleteButtonView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/CustomView/ShowDeleteCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/InterestShowListCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/InterestShowListViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/InterestShowListViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/InterestShowListViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewModel.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/EmptyStates/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/EmptyStates/interest_show_empty.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/EmptyStates/interest_show_empty.imageset/Frame 2608742.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/EmptyStates/interest_show_empty.imageset/Frame 2608742@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/EmptyStates/interest_show_empty.imageset/Frame 2608742@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/EmptyStates/my_show_empty.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/EmptyStates/my_show_empty.imageset/Frame 2608755.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/EmptyStates/my_show_empty.imageset/Frame 2608755@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/EmptyStates/my_show_empty.imageset/Frame 2608755@3x.png
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#136 [Feature] #123 드롭다운 UI 및 로직 작성
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Domain/UseCase/AllPerformance/AllPerformanceUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/AllPerformance/DefaultAllPerformanceUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/AllPerformanceViewController.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/AllPerformanceViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/CustomView/PerformanceFilterHeaderView.swift
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#137 [Feature] #24 커스텀 탭바
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/UI/SPTabBarItemView.swift
  ShowPot/ShowPot/Presentation/Common/BaseViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/MainTabController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsCoordinator.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_home.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_home.imageset/ic_home_24.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_home.imageset/ic_home_24@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_home.imageset/ic_home_24@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_home_filled.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_home_filled.imageset/ic_home_24_filled.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_home_filled.imageset/ic_home_24_filled@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_home_filled.imageset/ic_home_24_filled@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_my.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_my.imageset/ic_my_24.svg
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_my.imageset/ic_my_24@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_my.imageset/ic_my_24@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_my_filled.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_my_filled.imageset/ic_my_24_filled.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_my_filled.imageset/ic_my_24_filled@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_my_filled.imageset/ic_my_24_filled@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_show.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_show.imageset/ic_show_24.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_show.imageset/ic_show_24@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_show.imageset/ic_show_24@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_show_filled.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_show_filled.imageset/ic_show_24.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_show_filled.imageset/ic_show_24@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_show_filled.imageset/ic_show_24@3x.png
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#139 [Feature] 공연상세화면 UI구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/UIButton+Extension.swift
  ShowPot/ShowPot/Common/Extension/UIImageView+Extension.swift
  ShowPot/ShowPot/Common/Extension/UIStackView+Extension.swift
  ShowPot/ShowPot/Common/UI/AutoSizingCollectionView.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/AlarmSettingBottomSheetViewController.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/TicketingAlarmBottomSheetViewController.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/TicketingAlarmUpdateBottomSheetViewController.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/TicketingAlarmUpdateViewModel.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/TicketingAlarmViewModel.swift
  ShowPot/ShowPot/Common/UI/SPButtonStyle.swift
  ShowPot/ShowPot/Common/UI/SPDividerView.swift
  ShowPot/ShowPot/Domain/UseCase/AllPerformance/AllPerformanceUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/AllPerformance/DefaultAllPerformanceUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/MyAlarm/DefaultMyAlarmUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/ShowDetail/ShowDetailUseCase.swift
  ShowPot/ShowPot/Presentation/Common/BaseViewController.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/AllPerformanceCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/AllPerformanceViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedRecommendedPerformanceCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/ClosedShowListCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/ClosedShowListViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/InterestShowListCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/InterestShowListViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/ShowDetailLabelStackView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailArtistInfoView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailFooterView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailGenreInfoView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailInfoView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailPosterImageView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailSeatInfoView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailTicketInfoView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailTitleView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewModel.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Custom Color/Ticket Brand Chip/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Custom Color/Ticket Brand Chip/chip_default.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Custom Color/Ticket Brand Chip/chip_interpark.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Custom Color/Ticket Brand Chip/chip_melonticket.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/Custom Color/Ticket Brand Chip/chip_yes24.colorset/Contents.json
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#140 [Feature] #138 firebase 기능 추가
  .gitignore
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Application/AppDelegate.swift
  ShowPot/ShowPot/Resource/Info.plist
  ShowPot/ShowPot/ShowPot.entitlements
Labels: :sparkles: Feature

#141 [Feature] 설정화면 UI
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Environment.swift
  ShowPot/ShowPot/Common/UI/WebContent/WebContentCoordinator.swift
  ShowPot/ShowPot/Common/UI/WebContent/WebContentViewController.swift
  ShowPot/ShowPot/Common/UI/WebContent/WebContentViewHolder.swift
  ShowPot/ShowPot/Common/UI/WebContent/WebContentViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/CustomView/MenuCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/CustomView/LabelMenuCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsCoordinator.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_headphone.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_headphone.imageset/ic_FAQ_24.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_headphone.imageset/ic_FAQ_24@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_headphone.imageset/ic_FAQ_24@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_profile.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_profile.imageset/ic_profile_24.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_profile.imageset/ic_profile_24@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_profile.imageset/ic_profile_24@3x.png
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#142 [Feature] 홈화면 목데이터 및 로그인버튼 색상 변경
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeGenreCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
Labels: :sparkles: Feature

#151 [Fix] #145 공연상세화면 스크롤 인디케이터 히든
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailArtistInfoView.swift
Labels: :bug: Bug

#149 [Fix] #144 알림성공 시 스낵바 표출
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/TicketingAlarmBottomSheetViewController.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/TicketingAlarmUpdateBottomSheetViewController.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/TicketingAlarmUpdateViewModel.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/TicketingAlarmViewModel.swift
  ShowPot/ShowPot/Domain/UseCase/MyShow/MyShowAlarmUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/MyShow/MyShowUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
Labels: :bug: Bug

#153 [Hotfix] SwiftLint 경고오류 수정
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
Labels: :bug: Bug

#152 [Fix] #147 마이페이지 최근공연 삭제
  ShowPot/ShowPot/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/MyPage/MyPageUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewModel.swift
Labels: :bug: Bug

#157 [Feature] #155 로그인 관련 데이터 관리 로직 개발
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Application/AppDelegate.swift
  ShowPot/ShowPot/Common/LoginState.swift
  ShowPot/ShowPot/Common/TokenManager.swift
  ShowPot/ShowPot/Data/KeyChain/KeyChainAccount.swift
  ShowPot/ShowPot/Data/KeyChain/KeyChainError.swift
  ShowPot/ShowPot/Data/KeyChain/KeyChainManager.swift
Labels: :sparkles: Feature

#158 [Feature] #156 카카오 로그인 API 연동
  .gitignore
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/UI/SPSnackBar.swift
  ShowPot/ShowPot/Data/Network/APIClient.swift
  ShowPot/ShowPot/Data/Network/SPTargetType.swift
  ShowPot/ShowPot/Domain/Entity/Auth/Request/SignInRequest.swift
  ShowPot/ShowPot/Domain/Entity/Auth/Response/SignInResponse.swift
  ShowPot/ShowPot/Domain/Entity/Show/Request/SampleRequest.swift
  ShowPot/ShowPot/Domain/Entity/Show/Response/SampleResponse.swift
  ShowPot/ShowPot/Domain/Entity/Show/Response/ShowListResponse.swift
  ShowPot/ShowPot/Domain/UseCase/Account/DefaultSignInUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/Account/Protocol/SignInUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/SubscribeArtist/SubscribeArtistViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/ShowAlarmButtonView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/Subscribe/Genre/SubscribeGenreViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/CustomView/MyPageHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewModel.swift
  ShowPot/ShowPot/Resource/Configuration/ShowPot-Debug.xcconfig
  ShowPot/ShowPot/Resource/Configuration/ShowPot-Release.xcconfig
  ShowPot/ShowPot/Resource/Info.plist
Labels: :sparkles: Feature

#161 Feature/#159 genre subscribe api
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/LoginState.swift
  ShowPot/ShowPot/Data/Network/Infrastructure/APIType.swift
  ShowPot/ShowPot/Data/Network/SPGenreAPI.swift
  ShowPot/ShowPot/Domain/Entity/Genre/Request/GenreSubscribeRequest.swift
  ShowPot/ShowPot/Domain/Entity/Genre/Request/GenreUnsubscribeRequest.swift
  ShowPot/ShowPot/Domain/Entity/Genre/Response/GenreListResponse.swift
  ShowPot/ShowPot/Domain/Entity/Genre/Response/GenreSubscribeResponse.swift
  ShowPot/ShowPot/Domain/Entity/Genre/Response/GenreUnsubscribeResponse.swift
  ShowPot/ShowPot/Domain/UseCase/Genre/GenreSubscribeUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/Genre/GenreUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/Subscribe/Genre/GenreType.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/Subscribe/Genre/SubscribeGenreViewController.swift
Labels: :sparkles: Feature

#163 Feature/#160 homeapi
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/DateFormatterFactory.swift
  ShowPot/ShowPot/Data/Network/APIClient.swift
  ShowPot/ShowPot/Data/Network/SPTargetType.swift
  ShowPot/ShowPot/Domain/Entity/Artist/Request/UnsubscribeArtistListRequest.swift
  ShowPot/ShowPot/Domain/Entity/Artist/Response/ArtistListResponse.swift
  ShowPot/ShowPot/Domain/Entity/Show/Response/ShowListResponse.swift
  ShowPot/ShowPot/Domain/UseCase/Featured/DefaultFeaturedUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/SubscribeArtist/DefaultSubscribeArtistUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/SubscribeArtist/SubscribeArtistUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/AllPerformance/AllPerformanceViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/SubscribeArtist/SubscribeArtistViewModel.swift
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#165 [Feature] #162 토큰 재발급 임시 로직 개발
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Application/AppDelegate.swift
  ShowPot/ShowPot/Common/TokenManager.swift
  ShowPot/ShowPot/Data/Network/SPUserAPI.swift
  ShowPot/ShowPot/Domain/Entity/Users/Request/UserAccessRequest.swift
  ShowPot/ShowPot/Domain/Entity/Users/Request/UserLoginRequest.swift
  ShowPot/ShowPot/Domain/Entity/Users/Request/UserRefreshRequest.swift
  ShowPot/ShowPot/Domain/Entity/Users/Response/UserProfileResponse.swift
  ShowPot/ShowPot/Domain/Entity/Users/Response/UserTokenResponse.swift
Labels: :sparkles: Feature

#166 [Feature] #156 애플 로그인 구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
  ShowPot/ShowPot/ShowPot.entitlements
Labels: :sparkles: Feature

#167 [Feature] #164 검색 API 연동
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/DateFormatterFactory.swift
  ShowPot/ShowPot/Data/Network/SPArtistAPI.swift
  ShowPot/ShowPot/Data/Network/SPSearchAPI.swift
  ShowPot/ShowPot/Domain/Entity/Artist/Request/SearchArtistRequest.swift
  ShowPot/ShowPot/Domain/Entity/Artist/Request/SubscribeArtistListRequest.swift
  ShowPot/ShowPot/Domain/Entity/Artist/Request/SubscribeArtistRequest.swift
  ShowPot/ShowPot/Domain/Entity/Artist/Request/UnsubscribeArtistRequest.swift
  ShowPot/ShowPot/Domain/Entity/Artist/Response/SearchArtistResponse.swift
  ShowPot/ShowPot/Domain/Entity/Artist/Response/SubscribeArtistResponse.swift
  ShowPot/ShowPot/Domain/Entity/Artist/Response/UnsubscribeArtistResponse.swift
  ShowPot/ShowPot/Domain/Entity/Show/Request/SearchShowRequest.swift
  ShowPot/ShowPot/Domain/Entity/Show/Response/SearchShowResponse.swift
  ShowPot/ShowPot/Domain/UseCase/Featured/DefaultFeaturedUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/Search/DefaultSearchUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/Search/SearchUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/SubscribeArtist/DefaultSubscribeArtistUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Search/FeaturedSearchViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
Labels: :sparkles: Feature

#169 [Feature] #168 퍼블리싱가능한 노션링크로 수정
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#174 [Feature] #172 계정화면 및 API 연동
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/UI/SPSnackBar.swift
  ShowPot/ShowPot/Data/Network/SPUserAPI.swift
  ShowPot/ShowPot/Data/UserDefaults/UserDefaultsKey.swift
  ShowPot/ShowPot/Domain/Entity/EmptyModel.swift
  ShowPot/ShowPot/Domain/UseCase/Account/DefaultAccountUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/Account/DefaultSignInUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/Account/Protocol/AccountUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/Account/Protocol/SignInUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Account/AccountCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Account/AccountViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Account/AccountViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Account/AccountViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Account/CustomView/AccountHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/CustomView/MyPageHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewModel.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_logout.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_logout.imageset/ic_logout_24.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_logout.imageset/ic_logout_24@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_logout.imageset/ic_logout_24@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_profile_delete.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_profile_delete.imageset/ic_accountdelete_24.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_profile_delete.imageset/ic_accountdelete_24@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Icons/ic_profile_delete.imageset/ic_accountdelete_24@3x.png
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#179 [Feature] #175 내공연 및 공연상세
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/DateFormatterFactory.swift
  ShowPot/ShowPot/Common/NumberFormatterFactory.swift
  ShowPot/ShowPot/Data/Network/SPArtistAPI.swift
  ShowPot/ShowPot/Data/Network/SPShowAPI.swift
  ShowPot/ShowPot/Domain/Entity/Show/Request/ShowAlarmListRequest.swift
  ShowPot/ShowPot/Domain/Entity/Show/Response/ShowAlarmListResponse.swift
  ShowPot/ShowPot/Domain/Entity/Show/Response/ShowDetailResponse.swift
  ShowPot/ShowPot/Domain/UseCase/MyAlarm/DefaultMyAlarmUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/ShowDetail/ShowDetailUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/CustomView/MyUpcomingTicketingHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailSeatInfoView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/CustomView/StackSubViews/ShowDetailTicketInfoView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
Labels: :sparkles: Feature

#180 [Feature] #171 아티스트 구독 API 연동
  ShowPot/ShowPot/Data/Network/SPArtistAPI.swift
  ShowPot/ShowPot/Domain/UseCase/Featured/DefaultFeaturedUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/SubscribeArtist/DefaultSubscribeArtistUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/SubscribeArtist/SubscribeArtistUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/SubscribeArtist/SubscribeArtistViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/SubscribeArtist/SubscribeArtistViewModel.swift
Labels: :sparkles: Feature

#182 [Feature] #177 알림공연 & 관심공연 API 연결
  ShowPot/ShowPot/Common/Extension/Date+Extension.swift
  ShowPot/ShowPot/Common/TokenManager.swift
  ShowPot/ShowPot/Domain/UseCase/InterestShow/DefaultInterestShowUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/MyShow/MyShowAlarmUseCase.swift
Labels: :sparkles: Feature

#183 [Config] #11 Privacy Manifest 파일 생성
  ShowPot/PrivacyInfo.xcprivacy
  ShowPot/ShowPot.xcodeproj/project.pbxproj
Labels: :wrench: Config

#185 [Fix] #178 티켓팅알림 함수인자 showId추가
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/TicketingAlarmUpdateViewModel.swift
  ShowPot/ShowPot/Common/UI/BottomSheet/TicketingAlarm/TicketingAlarmViewModel.swift
  ShowPot/ShowPot/Data/Network/SPShowAPI.swift
  ShowPot/ShowPot/Domain/UseCase/MyShow/MyShowAlarmUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/MyShow/MyShowUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
Labels: :bug: Bug

#189 [Feature] #188 로그인 성공/실패 시 pop 혹은 스낵바 표출
  ShowPot/ShowPot/Common/UI/SPSnackBar.swift
  ShowPot/ShowPot/Domain/UseCase/Account/DefaultSignInUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#191 [Bugfix] #187 알람설정 안되는 문제 해결
  ShowPot/ShowPot/Common/TokenManager.swift
  ShowPot/ShowPot/Data/Network/SPShowAPI.swift
  ShowPot/ShowPot/Domain/Entity/Show/Request/ShowAlertRequest.swift
  ShowPot/ShowPot/Domain/UseCase/MyShow/MyShowAlarmUseCase.swift
Labels: :bug: Bug

#193 [Feature] #190 화면 진입 시 최신화 로직 추가
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/SubscribeArtist/SubscribeArtistViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/SubscribeArtist/SubscribeArtistViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/ClosedShowListViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ClosedShow/ClosedShowListViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/CustomView/MyAlarmEmptyView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/InterestShowListViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/InterestShowListViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
Labels: :sparkles: Feature

#194 [Bugfix] #115 홈화면 헤더/푸터 뷰 터치시 화면 중복 push 문제 수정
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWatchTheFullPerformanceFooterView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWithButtonHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
Labels: :bug: Bug
