Repository YAPP-Github/24th-App-Team-3-iOS, pull requests merged in 2024-07, with the labels that each got.

#41 [Feature] 탭바 구현 사전작업
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Presentation/Scene/Login/LoginCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/ViewController/FeaturedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/ViewModel/FeaturedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ViewController/SavedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ViewModel/SavedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/ViewController/SettingsViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/ViewModel/SettingViewModel.swift
Labels: :sparkles: Feature

#43 [Feature] #7 코디네이터 리팩토링 및 탭바 구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Application/AppCoordinator.swift
  ShowPot/ShowPot/Application/SceneDelegate.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/MainTabController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/MainTabCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/MainTabViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
Labels: :sparkles: Feature

#38 [Feature] #37 폰트에 따른 letterSpacing, lineHeight값 조절을 위한 Extention함수 구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/NSAttributedString+Extension.swift
  ShowPot/ShowPot/Common/Extension/UILabel+Extension.swift
Labels: :sparkles: Feature

#48 [OMLK-18] 소셜로그인 화면 UI 구성
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/google_white.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Color/kakaoYellow.colorset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/Group 1171275072.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/Group 1171275072.imageset/Group 1171275072.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/Group 1171275072.imageset/Group 1171275072@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/Group 1171275072.imageset/Group 1171275072@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/apple.imageset/Apple Logo.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/apple.imageset/Apple Logo@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/apple.imageset/Apple Logo@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/apple.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/google.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/google.imageset/logo googleg 48dp.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/google.imageset/logo googleg 48dp@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/google.imageset/logo googleg 48dp@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/kakao.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/kakao.imageset/Frame 2608701.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/kakao.imageset/Frame 2608701@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/login/kakao.imageset/Frame 2608701@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/logo/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/logo/Showpot.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/logo/Showpot.imageset/Showpot.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/logo/Showpot.imageset/Showpot@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/logo/Showpot.imageset/Showpot@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/kakao_login_medium_narrow.imageset/kakao_login_medium_narrow.png
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#54 [Feature] #37 letterSpacing, lineHeight값 적용을 위한 Extension 오류 수정
  ShowPot/ShowPot/Common/Extension/NSAttributedString+Extension.swift
  ShowPot/ShowPot/Common/Extension/UILabel+Extension.swift
  ShowPot/ShowPot/Common/Font/ENFont.swift
  ShowPot/ShowPot/Common/Font/KRFont.swift
  ShowPot/ShowPot/Common/Font/LanguageFont.swift
Labels: :bug: Bug

#57 [Package] #56 KingFisher SPM의존성 추가
  ShowPot/ShowPot.xcodeproj/project.pbxproj
Labels: :package: Package

#52 [Feature] [OMLK-17] 온보딩 화면 UI 개발
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/NSAttributedString+Extension.swift
  ShowPot/ShowPot/Common/Extension/UILabel+Extension.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/CustomView/OnboardingCarouselCell.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/MainTabController.swift
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/onboarding_1.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/onboarding_1.imageset/onboarding-1.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/onboarding_1.imageset/onboarding-1@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/onboarding_1.imageset/onboarding-1@3x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/onboarding_2.imageset/Contents.json
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/onboarding_2.imageset/onboarding-2.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/onboarding_2.imageset/onboarding-2@2x.png
  ShowPot/ShowPot/Resource/Assets.xcassets/Image/onboarding_2.imageset/onboarding-2@3x.png
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#59 [Feature] #37 소셜로그인 화면 자간 및 줄높이 적용
  ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
Labels: :sparkles: Feature

#64 [Refactor] #46 reuseIdentifier 지정 코드 추가
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/UI/Protocol/ReusableCell.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/CustomView/OnboardingCarouselCell.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewHolder.swift
Labels: :recycle: Refactor

#71 #70 ReusableCell 프로토콜 header footer 추가 대응
  ShowPot/ShowPot/Common/UI/Protocol/ReusableCell.swift
Labels: :sparkles: Feature

#72 [Fix] #68 폰트 line height & letter spacing 임시값으로 수정
  ShowPot/ShowPot/Common/Font/KRFont.swift
Labels: :bug: Bug

#73 [Feature] #49 userdefaults 관리 로직 개발
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Data/UserDefaults/UserDefaultsKey.swift
  ShowPot/ShowPot/Data/UserDefaults/UserDefaultsManager.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/MainTabController.swift
Labels: :sparkles: Feature

#62 [Feature][OMLK-43] 홈 화면관련 UI 구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/UI/PaddingLabel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedOnlyTitleHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceWithTicketOnSaleSoonCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedRecommendedPerformanceCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSearchButton.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeGenreCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWatchTheFullPerformanceFooterView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWithButtonHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#81 [Package] #74 swiftlint 추가
  ShowPot/.swiftlint.yml
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Application/AppDelegate.swift
  ShowPot/ShowPot/Application/SceneDelegate.swift
  ShowPot/ShowPot/Common/Font/ENFont.swift
  ShowPot/ShowPot/Common/Font/KRFont.swift
  ShowPot/ShowPot/Common/LogHelper.swift
  ShowPot/ShowPot/Common/UI/PaddingLabel.swift
  ShowPot/ShowPot/Data/UserDefaults/UserDefaultsManager.swift
  ShowPot/ShowPot/Presentation/Common/BaseViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedOnlyTitleHeaderView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceWithTicketOnSaleSoonCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedRecommendedPerformanceCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWatchTheFullPerformanceFooterView.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewHolder.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewHolder.swift
Labels: :package: Package

#86 [Config] #82 앱 아이콘 이미지 등록
  ShowPot/ShowPot/Resource/Assets.xcassets/AppIcon.appiconset/Appicon.png
  ShowPot/ShowPot/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: :wrench: Config

#85 [Feature] #69 BaseViewController에 default BGColor 적용
  ShowPot/ShowPot/Presentation/Common/BaseViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Saved/SavedViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
Labels: :sparkles: Feature, :recycle: Refactor

#84 [Feature] #47 SnackBar 기능 구현
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/UIButton+Trigger.swift
  ShowPot/ShowPot/Common/Extension/UIView+UIGestureRecognizer.swift
  ShowPot/ShowPot/Common/UI/Base/PaddingLabel.swift
  ShowPot/ShowPot/Common/UI/Base/SnackBar.swift
  ShowPot/ShowPot/Common/UI/SPSnackBar.swift
  ShowPot/ShowPot/Common/UI/SampleUI.swift
  ShowPot/ShowPot/Resource/Localizable/Localizable.strings
  ShowPot/ShowPot/Resource/Localizable/Strings+Generated.swift
Labels: :sparkles: Feature

#89 [Refactor] #83 온보딩 화면 UseCase활용해 리팩토링
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Domain/UseCase/Onboarding/DefaultOnboardingUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/Onboarding/OnboardingUseCase.swift
  ShowPot/ShowPot/Domain/UseCase/SampleUseCase.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/CustomView/OnboardingCarouselCell.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingCoordinator.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewController.swift
  ShowPot/ShowPot/Presentation/Scene/Onboarding/OnboardingViewModel.swift
Labels: :recycle: Refactor

#92 [Feature] #79 Linear Gradient 적용을 위한 공통 함수
  ShowPot/ShowPot.xcodeproj/project.pbxproj
  ShowPot/ShowPot/Common/Extension/UIView+CALayer.swift
  ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceWithTicketOnSaleSoonCell.swift
Labels: :sparkles: Feature
